### PR TITLE
Feature/70 create api docs

### PR DESCRIPTION
**Pull request by cmcWebCode40**
- Modified `jsdoc.json` config file

resolves issue #70

### CODE REVIEW

**Comment by tahpot** [comment]
@cmcWebCode40 I've run this locally, but it appears lots of the classes are still not available.

For example:

- https://github.com/verida/verida-js/blob/main/packages/client-ts/src/context/engines/verida/messaging/engine.ts
- https://github.com/verida/verida-js/blob/main/packages/client-ts/src/context/engines/verida/messaging/inbox.ts
- https://github.com/verida/verida-js/blob/main/packages/client-ts/src/context/engines/verida/messaging/outbox.ts
- https://github.com/verida/verida-js/blob/main/packages/client-ts/src/context/engines/verida/database/db-encrypted.ts

**Comment by cmcWebCode40** [comment]
> * Modified `jsdoc.json` config file
> 
> resolves issue #70

@tahpot, I'm currently having issues displaying all the classes, it does not display more than 7 classes, I have also exported all default class names correctly. have you experienced issues like this working with  `better-docs`  ?.

**Comment by tahpot** [comment]
@cmcWebCode40 I have never used better-docs sorry. I chose it very quickly as it looked like the nicest looking solution that supported `typescript`.

@nick-verida Is it worth us looking at a different library?

**Comment by nick-verida** [comment]
@cmcWebCode40 do you know where this is at? Is it waiting for @tahpot to take another look at it?

**Comment by tahpot** [comment]
@nick-verida @cmcWebCode40 

I have merged this in as the core requirement of getting the API docs is working.

It still needs more complete API docs added to the code. I have created a task here https://github.com/verida/verida-js/issues/114

**Pull request merged**
